### PR TITLE
Better export situation, better namespacing for datasets code

### PR DESCRIPTION
**Pull request by dcrescim**

### CODE REVIEW

**Review by yawetse — APPROVED** [review]
love this!

do you want to namespace the exports to mirror sklearn?

e.g. LinearRegressor would be namespace under linear_model so the import would look more like? 
```python
from sklearn.linear_model import LinearRegression
```

**Comment by dcrescim** [comment]
Yeah we should definitely match the sklearn namespacing @yawetse

**Comment by DirkToewe** [comment]
> ```js
> from sklearn.linear_model import LinearRegression
> ```

I was thinking among the same lines. But how would that look in TS/JS?

```js
import { linear_model } from 'scikitjs'
const { LinearRegression } = linear_model
```

Or would there be a more concise way?

**Review by DirkToewe — APPROVED** [review]

**Comment by dcrescim** [comment]
Yeah, I'm kinda partial to not matching that part of the sklearn api, so that we can just write.

```
import { LinearRegression } from 'scikitjs'
```
without forcing the user to know that `LinearRegression` lives inside of `linear_model`

**Pull request merged**
