### PR TITLE
Update/danfojs version

### PR DESCRIPTION
**Pull request by risenW**
This PR updates Danfojs version to the latest Typescript release

### CODE REVIEW

**Comment by DirkToewe** [comment]
First of all: Amazing work transitioning to TypeScript! The PR is trying to merge into the `dev` branch. Is that intentional? The `dev` branch seem to be quite far behind the `main` branch.

**Comment by risenW** [comment]
> First of all: Amazing work transitioning to TypeScript! The PR is trying to merge into the `dev` branch. Is that intentional? The `dev` branch seem to be quite far behind the `main` branch.

Thanks! Oh I didn't realize. Is the main branch the latest? I can update that.

**Comment by DirkToewe** [comment]
Yes main should be the most up-to-date branch.

**Comment by risenW** [comment]
WON'T MERGE. I'll rebase it and push a new PR

**Pull request closed without merging**
