### PR TITLE
Renamed filenames to be snakecase

### PR DESCRIPTION
**Pull request by dcrescim**
As per @Lewuathe's suggestions changed our filenames to be snakecase everywhere. I agree that it's better because everything else in this repo is already snakeCase ("fitPredict", "trainTestSplit", etc...). 

3 major things:
1. Renamed all files to snakeCase -> "logistic.regression.ts" -> "logisticRegression.ts"
2. Fixed up Contributing Doc to match 
3. Removed all references to opensource9ja in favor of javascriptdata (we changed the org name, thanks @risenW)

### CODE REVIEW

**Comment by DirkToewe** [comment]
This may cause all kinds of nightmares on Windows machines :frowning_face:. Windows file systems are case-agnostic afaik.

**Comment by dcrescim** [comment]
I just talked to Dirk over Zoom, and I think we are good to go with snakeCase. After looking at some big libraries like React (https://github.com/facebook/react/tree/main/packages/react/src) and Typescript (https://github.com/microsoft/TypeScript/tree/main/scripts) which is run by Microsoft, it seems that plenty of folks are mixing capital letters in with lowercase for filenames.

That being said, if it does every become a problem on Windows / Ubuntu / wherever, I will happily change it to dashes or underscores. It's all the same to me :)

You're the man @DirkToewe for bringing this to my attention!

**Comment by DirkToewe** [comment]
One more question: For classes e.g. `LassoRegression`, should it be `lassoRegression.ts` or `LassoRegression.ts`?

**Comment by dcrescim** [comment]
No opinion either way. What do you guys think?

**Pull request merged**
