### PR TITLE
Model saving and loading

### PR DESCRIPTION
**Pull request by steveoni**
This pr implemented a generic serializer for all provided classes wrt to #165

### CODE REVIEW

**Comment by steveoni** [comment]
@dcrescim started the implementation for the save and load model. the generic class can be extended by all object which requires serialization. 

I will apply it to some of the models and tests.

what do you think about the class name `Serialize`?

**Comment by dcrescim** [comment]
@steveoni I think the name `Serialize` works great! Looking forward to this. This is gonna be huge man 😄

**Comment by steveoni** [comment]
@dcrescim this pr is ready for review.

**Review by dcrescim — APPROVED** [review]
@steveoni Awesome work! This is great dude. This is definitely an accept from me :)

Question: Do we need to add "optimizerType", and "lossType" to the declaration of the SGD models? With those added, it is now possible for the variables in "optimizerType" to be out of sync with those in "modelCompileArgs" that is used to define "LassoRegression", "ElasticNet", etc. I'm ok with this solution, I'm just hoping that there maybe something more clever we can do, to avoid duplicating that info.

**Comment by steveoni** [comment]
> @steveoni Awesome work! This is great dude. This is definitely an accept from me :)
> 
> Question: Do we need to add "optimizerType", and "lossType" to the declaration of the SGD models? I'm wondering if now it's possible to get those out of sync with the "modelCompileArgs" that is used to define "LassoRegression", "ElasticNet", etc. I'm ok with this solution, I'm just hoping that there maybe something more clever we can do, to avoid duplicating that info.

@dcrescim i also thought of thesame thing better way not to duplicate it, but is hard to generate the loss and optimizer type from the function, they are anonymous function.

**Comment by dcrescim** [comment]
Totally agree @steveoni. Let's merge this for now, and if we think of a better way, then we can explore that.

**Pull request merged**
